<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="MailKit" />
    <PackageReference Include="Scriban" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="ArchitectureTests" />
	<InternalsVisibleTo Include="Infrastructure.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Email\Templates\*.html" />
  </ItemGroup>

</Project>
